build:
	swiftc -c main.swift src/day01/day01.swift src/day02/day02.swift src/day03/day03.swift src/day04/day04.swift src/day05/day05.swift src/day06/day06.swift src/day07/day07.swift src/day08/day08.swift -module-name AdventOfCode -O
	swiftc -emit-executable *.o -o adventOfCode
	rm *.o